# Redis数据库索引（默认为0）
spring:
  redis:
    database: 0
  # Redis服务器地址
    host: 47.105.125.178
  # Redis服务器连接端口
    port: 6379
  # Redis服务器连接密码（默认为空）
    password: 111111
  # 连接超时时间（毫秒）
    jedis.pool.max-wait: -1
    timeout: 5000

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
        # 主库数据源
        master:
            url: jdbc:mysql://47.105.125.178:3306/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
            username: root
            password: xieyang123
        # 从库数据源
        slave:
            # 从数据源开关/默认关闭
            enabled: false
            url:
            username:
            password:
        # 初始连接数
        initial-size: 10
        # 最大连接池数量
        max-active: 100
        # 最小连接池数量
        min-idle: 10
        # 配置获取连接等待超时的时间
        max-wait: 60000
        # 打开PSCache，并且指定每个连接上PSCache的大小
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 1 FROM DUAL
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        stat-view-servlet:
            enabled: true
            url-pattern: /monitor/druid/*
        filter:
            stat:
                log-slow-sql: true
                slow-sql-millis: 1000
                merge-sql: false
            wall:
                config:
                    multi-statement-allow: true


  rabbitmq.host: 119.3.91.32
  rabbitmq.port: 5672
  rabbitmq.username: guest
  rabbitmq.password: guest

mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.cullen.demo
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:mapper/*/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mapper/mybatis-config.xml


# 开发环境配置
server:
  # 服务端口
  port: 8080
  servlet:
    # 项目contextPath
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 200
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30


